// <auto-generated />
namespace ContactManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Chnagephonenumbertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chnagephonenumbertype));
        
        string IMigrationMetadata.Id
        {
            get { return "202009271002479_Chnage phonenumber type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
